version: '3.9'

services:
    java_db:
        image: postgres:13.3
        container_name: java_db
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=java_db
        ports:
            - 5432:5432
        volumes:
            - ./data:/var/lib/postgresql/data

